### ISSUE TITLE
Database Query Decode Issue

### ISSUE THREAD

**Issue by emelone16** [chojnac/NotionSwift#14]
When calling `.databaseQuery`, I am seeing the following error when trying to decode the response from the API:

```
failure(NotionSwift.NotionClientError.decodingError(Swift.DecodingError.typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "next_cursor", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil))))
2021-12-02 22:17:45.815971-0500 notion-viewer[8562:5939368] [boringssl] boringssl_metrics_log_metric_block_invoke(144) Failed to log metrics
```

It looks like in the `ListResponse` struct, this package defines `nextCursor` with type `Int?`. However in the API response from the current version of the Notion API, it is returning a string for this value.

It looks like simply changing this type to `String?` should fix this. Happy to make a PR to fix this, but wanted to post the issue here first to see what the creator thinks.

**Comment by chojnac** [comment]
Hey, thanks for spotting and reporting the issue. It is fixed in the main branch and in the latest.
