### ISSUE TITLE
Adding new row to multi-column database in notion

### ISSUE THREAD

**Issue by corybohon** [chojnac/NotionSwift#17]
Is there currently a way with this package to add a new single row to a multi-column database in Notion and map the new values to named columns in the database? Sort of confused on the documentation around this and unsure if it's possible. Thanks for any help, and thanks for creating this great project.

**Comment by chojnac** [comment]
Sadly there isn't at the moment, but give me a few days to fix that :)

**Comment by chojnac** [comment]
Ok, so the change is ready in the `main` branch. I've also added an example in the readme/PR to demonstrate how to build blocks and append content to a document (block id).  
In a few days, I will also prepare a new release (I have a few things more to add before releasing the new version)

**Comment by corybohon** [comment]
This looks awesome! Thank you!

**Comment by chojnac** [comment]
released in version 0.6.0
