### ISSUE TITLE
Rename Environment

### ISSUE THREAD

**Issue by JaydenIrwin** [chojnac/NotionSwift#21]
Could you rename `Environment`? It conflicts with SwiftUI and gives the error "'Environment' is ambiguous for type lookup in this context" when I try to use `@Environment` variables.

**Comment by chojnac** [comment]
Ok, I will try to do something with this. Meantime to resolve the issue, you can use `@SwiftUI.Environment` in your code.

**Comment by chojnac** [comment]
Fixed
