### ISSUE TITLE
API request fails when database contains a Double value not Int

### ISSUE THREAD

**Issue by baxi87** [chojnac/NotionSwift#26]
<img width="253" alt="Screenshot 2022-05-29 at 12 21 47" src="https://user-images.githubusercontent.com/71763675/170853581-f6eb408a-692f-47be-bb38-ecef0ea9aec3.png">
<img width="583" alt="Screenshot 2022-05-29 at 12 21 57" src="https://user-images.githubusercontent.com/71763675/170853582-a7311ddd-5778-4090-8ec6-90d8e272aed2.png">

When trying to query a database that contains a double value (in the example given: 1,000.50) as opposed to a rounded Integer value (1000.00), the request fails and an "Error 3" is returned. 

This happens on Formula property types, number property types and rollup types.

**Comment by esroberts** [comment]
Seeing a similar issue.  With the following code I am getting the subsequent error:  

```
let notion = NotionClient(accessKeyProvider: StringAccessKeyProvider(accessKey: notionToken))
    
let databaseId = Database.Identifier(databaseId)

notion.databaseQuery(databaseId: databaseId) { result in
    do {
        print(try result.get())
    } catch let error {
        print("Error: ", error)
 }
```

```
Error:  decodingError(Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "properties", intValue: nil), _JSONKey(stringValue: "Sleep Time", intValue: nil), CodingKeys(stringValue: "formula", intValue: nil), CodingKeys(stringValue: "number", intValue: nil)], debugDescription: "Parsed JSON number <8.4> does not fit in Int.", underlyingError: nil)))
```

This is for an existing table and I believe the field it's choking on is a Formula

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1750654/170905320-fcd8715f-7d44-4067-8d4c-e6e292f1d594.png">

I tried on a couple other of my existing databases with Formula and Rollup fields and got similar results.  I created a fresh DB with no Rollup or Formula fields and the call was successful.

**Comment by chojnac** [comment]
Thanks for the bug report, fix is on the way.

**Comment by esroberts** [comment]
Thanks @chojnac .  It looks like the fix works for some cases but I found another edge case where it's getting a similar error 

```Error:  decodingError(Swift.DecodingError.valueNotFound(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "properties", intValue: nil), _JSONKey(stringValue: "Songwriting Minutes", intValue: nil), CodingKeys(stringValue: "rollup", intValue: nil), CodingKeys(stringValue: "number", intValue: nil)], debugDescription: "Expected Int value but found null instead.", underlyingError: nil)))```

**Comment by chojnac** [comment]
@esroberts this [commit](https://github.com/chojnac/NotionSwift/commit/d9876f4c73cf90437b094b97c3da03aa2b7eede3) should fix the issue. Could you please try again from the latest 'main' branch?

**Comment by baxi87** [comment]
Legend. Thanks @chojnac

**Comment by esroberts** [comment]
@chojnac  Unfortunately it looks like a slightly different error now:

```
Error:  decodingError(Swift.DecodingError.valueNotFound(__C.NSDecimal, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "properties", intValue: nil), _JSONKey(stringValue: "Songwriting Minutes", intValue: nil), CodingKeys(stringValue: "rollup", intValue: nil), CodingKeys(stringValue: "number", intValue: nil)], debugDescription: "Expected NSDecimal value but found null instead.", underlyingError: nil)))```

The field in question is a rollup.   Here's a screenshot of the notion DB

<img width="510" alt="image" src="https://user-images.githubusercontent.com/1750654/171067810-83a92193-6475-42d6-a53a-02537072db5a.png">

I'm still learning Swift, but please let me know if there is more useful information I can provide

**Comment by chojnac** [comment]
@esroberts hey, could you please check your code with the library from this branch/PR https://github.com/chojnac/NotionSwift/pull/28 ?
 
In theory number value in rollup always should have a value, but it seems that it's not always true.
