### ISSUE TITLE
Unable to update database due to missing icons

### ISSUE THREAD

**Issue by JaydenIrwin** [chojnac/NotionSwift#30]
I want to update the properties on my database, but am unable to because of Notion error 1.

`let request = DatabaseUpdateRequest(title: database.title, icon: database.icon, cover: database.cover, properties: updatedProperties)`

> body validation failed. Fix one: body.icon.emoji should be defined, instead was undefined. body.icon.external should be defined, instead was undefined.

I'm not sure why the icons would matter when updating properties. But anyway, I got the error with a database that had only an icon and no cover. And also on a database with both an icon and cover image.

**Comment by chojnac** [comment]
Can you check what is the value in `database.icon` property? 
This error indicates that there is an invalid value provided. Based on my tests for the icon field, only 2 values are accepted - `IconFile.external` and `IconFile.emoji`. The third case (`IconFile.file`) can be set only from the web interface. So when a document has `IconFile.file` and then you try to put it again from API you will get an error.

**Comment by JaydenIrwin** [comment]
Yes it was an `IconFile.file`. Oh I see, I should pass `nil` as the icon, and it won't be updated. I was thinking `nil` would delete the icon, but now I understand. Thanks for the help!
