### ISSUE TITLE
Create page decoding fails for null link property

### ISSUE THREAD

**Issue by andreabusi** [chojnac/NotionSwift#31]
I'm using `pageCreate` to create a page inside a database with some properties. Create request succeed, but the response parse fails due to a null link property.

This is the error message that I get:

```
[ERROR] decoding: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "properties", intValue: nil), _JSONKey(stringValue: "GCal Link", intValue: nil), CodingKeys(stringValue: "url", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
```

On the Notion database, `GCal link` is a URL property, that is usually empty:

<img width="360" alt="Screenshot 2022-08-15 at 10 53 01" src="https://user-images.githubusercontent.com/847860/184605920-8b600214-c7c2-4073-9baa-866e6b25dd06.png">

I'm able to reproduce the issue every time, let me know if you need other info!

**Comment by chojnac** [comment]
Fixed, what a stupid mistake 🤦

**Comment by chojnac** [comment]
Also @andreabusi thanks for reporting it 💯

**Comment by andreabusi** [comment]
Nice! Thanks for the quick fix!
