### ISSUE TITLE
OAuth Support

### ISSUE THREAD

**Issue by undecoded-coder** [chojnac/NotionSwift#34]
Thanks for what you're doing with this project.

In the README it is stated:
> Currently, this library supports only the "internal integration" authorization mode.

I'm not too familiar with OAuth, but from the Notion docs it seemed as though once the OAuth flow has succeeded you are simply given a token which can be used in essentially the same way as a personal token.
Are there differences in how you interact with the API when using OAuth (such that changes would be needed in this package in order to support it)?

**Comment by chojnac** [comment]
There are no differences if you use the token obtain from the OAuth flow.

**Comment by undecoded-coder** [comment]
Great, thanks for clarifying. 
Maybe the quoted text from the README could be updated to make that clearer.
