### ISSUE TITLE
DatabaseFilter with .number

### ISSUE THREAD

**Issue by jraymonds86** [chojnac/NotionSwift#39]
This doesn't seem to make sense:

```
extension DatabasePropertyFilter {
    public enum NumberCondition {
        case equals(Int)
        case doesNotEqual(Int)
        case greaterThan(Int)
        case lessThan(Int)
        case greaterThanOrEqualTo(Int)
        case lessThanOrEqualTo(Int)
        case isEmpty
        case isNotEmpty
    }
 }
```

number for Notion is a Decimal and not an integer. Plus, trying to create a filter with (an example Int):

`.property(name: "theKey", type: .number(.equals(10000)))`

Fails to query at all: NotionSwift.NotionClientError error 1.

Oddly, using the example from your test code, this works:

`.property(name: "theKey", type: .number(.greaterThanOrEqualTo(10000)))`

However, it still has the problem of being an Int instead of a Decimal

**Comment by chojnac** [comment]
@jraymonds86 thank you for finding and reporting this bug, much appreciated!

issue should be fixed now fixed
